---
- name: Add br_netfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: Enable ipv4 forwarding, iptable bridge
  sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_file: /etc/sysctl.d/11-kubernetes.conf
    sysctl_set: yes
    reload: yes
  loop:
    - net.ipv4.ip_forward
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables