- name: Add Kubernetes Repository
  yum_repository:
    name: Kubernetes
    file: Kubernetes
    description: Kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    enabled: yes
    gpgcheck: yes

- name: Add epel-release
  yum:
    name: epel-release
    state: present

- name: Add python-pip and python-openshift
  yum:
    name:
      - python-pip
      - python-openshift
    state: present

- name: Install Kubelet, Kubeadm, Kubectl
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - kubelet-{{ kube_version }}
      - kubeadm-{{ kube_version }}
      - kubectl-{{ kube_version }}

- name: Enable and Run Kubelet
  systemd:
    name: kubelet
    enabled: yes
    state: started