---
- name: Install firewalld
  yum:
    name: firewalld
    state: present

- name: Enable firewall service
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: Enable firewall port for jenkins
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop:
    - 80/tcp
    - 8080/tcp
    - 443/tcp
